dataset: S-FFSD

trainfeature: /content/drive/MyDrive/data_anti_fraud/trf_2d.npy
trainlabel: /content/drive/MyDrive/data_anti_fraud/trl_2d.npy
testfeature: /content/drive/MyDrive/data_anti_fraud/tef_2d.npy
testlabel: /content/drive/MyDrive/data_anti_fraud/tel_2d.npy

test_size: 0.2

epochs: 30
batch_size: 512
lr: 0.001
device: cpu